# Generated by Django 4.0.1 on 2022-01-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discord_username',
            field=models.CharField(default=None, max_length=100, verbose_name='Username в discord'),
        ),
        migrations.AddField(
            model_name='student',
            name='telegram_username',
            field=models.CharField(default=None, max_length=100, verbose_name='Username в telegram'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skill_level',
            field=models.CharField(choices=[('novice', 'Новичок'), ('novice+', 'Новичок+'), ('junior', 'Джун')], max_length=50, verbose_name='Уровень навыков'),
        ),
    ]
