# Generated by Django 4.0.1 on 2022-01-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterModelOptions(
            name='projectteam',
            options={'verbose_name': 'Команда проекта', 'verbose_name_plural': 'Команды проектов'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='telegram_username',
        ),
    ]
