# Generated by Django 4.0.1 on 2022-01-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_alter_project_name_alter_projectteam_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='project_date',
            field=models.CharField(blank=True, choices=[(3, '2022-01-17'), (4, '2022-01-24')], max_length=50, verbose_name='Дата начала проекта'),
        ),
    ]
