# Generated by Django 4.0.1 on 2022-01-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_student_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='project_date',
            field=models.CharField(blank=True, choices=[('2022-01-17', '2022-01-17'), ('2022-01-24', '2022-01-24')], max_length=50, verbose_name='Дата начала проекта'),
        ),
    ]
