# Generated by Django 4.0.1 on 2022-01-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_remove_student_project_date_project_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_date',
            field=models.DateField(blank=True, verbose_name='Дата начала проекта'),
        ),
    ]
