# Generated by Django 4.0.1 on 2022-01-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_alter_project_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_week',
            field=models.IntegerField(choices=[(1, 'Первая неделя'), (2, 'Вторая неделя')], default=1, verbose_name='Текущая неделя проекта'),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_week',
            field=models.IntegerField(choices=[(1, 'Первая неделя'), (2, 'Вторая неделя')], default=1, verbose_name='Предпочитаемая неделя проекта'),
        ),
    ]
