# Generated by Django 4.0.1 on 2022-01-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_project_current_week_student_preferred_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanager',
            name='projects_time_begin',
            field=models.TimeField(null=True, verbose_name='Начало времени проектов'),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='projects_time_end',
            field=models.TimeField(null=True, verbose_name='Конец времени проектов'),
        ),
    ]
