# Generated by Django 4.0.1 on 2022-01-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_alter_projectmanager_projects_time_begin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='excluded_pms',
            field=models.ManyToManyField(related_name='excluded_by', to='tgbot.ProjectManager', verbose_name="ПМ'ы с которыми не должен попасть"),
        ),
        migrations.AddField(
            model_name='student',
            name='excluded_students',
            field=models.ManyToManyField(related_name='excluded_by', to='tgbot.Student', verbose_name='Ученики с которыми не должен попасть'),
        ),
        migrations.AddField(
            model_name='student',
            name='included_pms',
            field=models.ManyToManyField(related_name='included_by', to='tgbot.ProjectManager', verbose_name="ПМ'ы с которыми должен попасть"),
        ),
        migrations.AddField(
            model_name='student',
            name='included_students',
            field=models.ManyToManyField(related_name='included_by', to='tgbot.Student', verbose_name='Ученики с которыми должен попасть'),
        ),
    ]
