# Generated by Django 4.0.1 on 2022-01-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0009_student_excluded_pms_student_excluded_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='included_pms',
        ),
        migrations.RemoveField(
            model_name='student',
            name='included_students',
        ),
    ]
